MAC:
  DIM: 512
  EMBD_DIM: 300
  SELF_ATT: False
  MEMORY_GATE: False
  MEMORY_GATE_BIAS: 0.0
  MAX_ITER: 12
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE: 64
  FEATURES_PATH: "/home/cristobal/datasets/CLEVR_v1.0"
SOLVER:
  EPOCHS: 10
  LR: 0.0001
  GRAD_CLIP: 0
DEVICE: "cuda"
