MAC:
  DIM: 512
  EMBD_DIM: 300
  DROPOUT_PROB: 0.15
  SELF_ATT: False
  MEMORY_GATE: False
  MEMORY_GATE_BIAS: 0.0
  USE_ACT: False
  MAX_ITER: 12
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE: 64
SOLVER:
  EPOCHS: 10
  LR: 0.0001
  GRAD_CLIP: 0
DEVICE: "cuda"
